# Generated by Django 4.2.5 on 2023-10-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_terror_descripcion_terror_imagenterror_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terror',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
