# Generated by Django 4.2.5 on 2023-09-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_carreras_cursos_servicio_delete_curso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='formapago',
            new_name='forma_de_pago',
        ),
    ]
