# Generated by Django 4.2.5 on 2023-09-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_rename_formapago_servicio_forma_de_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='materia',
            new_name='modalidad',
        ),
    ]
