# Generated by Django 4.2.5 on 2023-10-12 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_imagenes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagenes',
        ),
    ]
