# Generated by Django 4.2.5 on 2023-10-12 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='terror',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='texto',
        ),
        migrations.AddField(
            model_name='comentario',
            name='comentario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='AppCoder.terror'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.CharField(max_length=40),
        ),
    ]
