# Generated by Django 4.2.5 on 2023-10-12 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_remove_comentario_terror_remove_comentario_texto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='usuario',
            new_name='nombre',
        ),
    ]
